In [6]:
import pandas as pd
import numpy as np

from pydataset import data

from scipy import stats


In [11]:
alpha = 0.05

# ex1

In [9]:
data = {
    "uses_a_macbook": [49, 20],
    "doesnt_use_a_macbook": [1, 30]
}
# Setting the index names
index_names = ["codeup_student", "not_codeup_student"]

In [25]:
# Creating the DataFrame
observed = pd.DataFrame(data, index=index_names).T
observed

codeup_student  not_codeup_student
uses_a_macbook                    49                  20
doesnt_use_a_macbook               1                  30

$H_0$: There is no relationship between whether a student is from codeup and whether they use a mac(independent).

$H_a$: There IS relationship between whether a student is from codeup and whether they use a mac(dependent).

In [26]:
chi2, p, dof, expected = stats.chi2_contingency(observed)

In [27]:
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[49 20]
 [ 1 30]]

Expected
[[34 34]
 [15 15]]

----
chi^2 = 36.6526
p     = 0.0000


In [28]:
if p < alpha:
    print('reject the null hypothesis')
else:
    print('fail to reject ')

reject the null hypothesis


# ex2

In [34]:
# Load the dataset and store it in the variable mpg.

from pydataset import data
mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [ ]:
alpha = .05

In [38]:
mpg.cyl.value_counts()

cyl
4    81
6    79
8    70
5     4
Name: count, dtype: int64

In [39]:
mpg.fl.value_counts()

fl
r    168
p     52
e      8
d      5
c      1
Name: count, dtype: int64

$H_0$: There is no relationship between the vehicles cylinder count  and it's fuel(independent).

$H_a$: There IS a relationship between the vehicles cylinder count  and it's fuel(dependent).

In [40]:
observed = pd.crosstab(mpg.cyl, mpg.fl)
observed

fl   c  d  e   p   r
cyl                 
4    1  3  0  22  55
5    0  0  0   0   4
6    0  1  1  17  60
8    0  1  7  13  49

In [41]:
chi2, p, dof, expected = stats.chi2_contingency(observed)

In [42]:
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[ 1  3  0 22 55]
 [ 0  0  0  0  4]
 [ 0  1  1 17 60]
 [ 0  1  7 13 49]]

Expected
[[ 0  1  2 18 58]
 [ 0  0  0  0  2]
 [ 0  1  2 17 56]
 [ 0  1  2 15 50]]

----
chi^2 = 19.2459
p     = 0.0828


In [44]:
if p < alpha:
    print('reject the null hypothesis')
else:
    print('fail to reject null hypothesis (no relationship)')

fail to reject null hypothesis (no relationship)


# ex3

In [45]:
alpha= .05

In [48]:
#3. Create a function named get_db_url. 
def get_db_url(username, host, password, database_name):
    return f'mysql+pymysql://{username}:{password}@{host}/{database_name}'

In [49]:
from env import host, username, password
url = get_db_url(username, host, password, 'employees')
pd.read_sql('select * from employees limit 5', url)

ModuleNotFoundError: No module named 'env'