In [109]:
import numpy as np
import pandas as pd
from scipy import stats

In [113]:
np.random.seed(123)

In [5]:
# How likely is it that you roll doubles when rolling two dice?
outcomes = [1,2,3,4,5,6]
n_trials = 1
1/6

0.16666666666666666

In [7]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls


array([[1, 1],
       [6, 4],
       [4, 5],
       ...,
       [6, 1],
       [4, 4],
       [6, 2]])

In [35]:
wins_by_trial = (rolls[][0] == rolls[][1])

NameError: name 'x' is not defined

In [40]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?
outcomes = ['H', 'T']
n_trials = 8
n_sims = 1000
eight_flips = np.random.choice(outcomes, (n_sims, n_trials))

In [41]:
eight_flips[:10]

array([['T', 'T', 'H', 'H', 'H', 'H', 'H', 'H'],
       ['H', 'H', 'H', 'H', 'H', 'T', 'H', 'T'],
       ['T', 'H', 'T', 'T', 'T', 'H', 'T', 'T'],
       ['H', 'T', 'T', 'H', 'T', 'H', 'T', 'T'],
       ['T', 'H', 'H', 'T', 'T', 'T', 'T', 'H'],
       ['T', 'T', 'T', 'H', 'H', 'T', 'T', 'H'],
       ['H', 'H', 'H', 'T', 'T', 'H', 'T', 'H'],
       ['T', 'H', 'H', 'H', 'T', 'H', 'H', 'H'],
       ['H', 'T', 'H', 'H', 'T', 'H', 'H', 'H'],
       ['T', 'H', 'H', 'T', 'T', 'H', 'H', 'T']], dtype='<U1')

In [45]:
(eight_flips == 'H')[:3]

array([[False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False],
       [False,  True, False, False, False,  True, False, False]])

In [48]:
(((eight_flips == 'H').sum(axis=1))==3).mean()

0.211

In [49]:
(((eight_flips == 'H').sum(axis=1))>3).mean()

0.641

In [65]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?
outcomes = ['DS', 'WD', 'WD', 'WD']
n_trials = 2
n_sims = 10000
two_boards = np.random.choice(outcomes, (n_sims, n_trials))

In [66]:
two_boards[:5]

array([['DS', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['DS', 'WD'],
       ['WD', 'WD']], dtype='<U2')

In [67]:
(((two_boards == ['DS']).sum(axis=1))==2).mean()


0.0615

In [114]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal)
# You'll need to make a judgement call on how to handle some of your values
μ = 3 #mean
σ = 1.5 #std
nrows=100
ncols=2
tarts_per_day = stats.norm(μ, σ)
tarts_per_day = np.random.normal(μ, σ,size=10000).reshape(-1,5)
(tarts_per_day.sum(axis=1)<=16).mean()


0.6065

In [134]:
# compare heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
μ1 = 178
σ1 = 8 #std

μ2 = 170 #mean
σ2 = 6 #std
nrows=10000
male_samples = np.random.normal(μ1 , σ1, nrows).reshape(-1,1)
female_samples = np.random.normal(μ2, σ2, nrows).reshape(-1,1)

In [135]:
male_samples[:10]

array([[178.4056179 ],
       [173.31773363],
       [167.68223086],
       [180.99673914],
       [190.08217118],
       [169.90917825],
       [175.95208061],
       [188.25819482],
       [178.42928576],
       [187.30809874]])

In [136]:
female_samples[:10]

array([[161.60277088],
       [177.84917489],
       [168.9220938 ],
       [166.79718947],
       [175.91923366],
       [165.02076661],
       [158.28401993],
       [163.89684322],
       [174.52265172],
       [169.33737041]])

In [137]:
(female_samples>male_samples).mean()

0.2126